name: Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Black
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install black
        run: pip install black

      - name: Check formatting
        run: black --check src/ tests/